//===-- QUIR.td - Entry point for MathOps bindings ------*- tablegen -*-===//
//
//
//===----------------------------------------------------------------------===//

#ifndef PYTHON_BINDINGS_QCS_OPS
#define PYTHON_BINDINGS_QCS_OPS

include "mlir/Bindings/Python/Attributes.td"
include "mlir/IR/OpBase.td"
include "Dialect/QCS/IR/QCSBase.td"
include "Dialect/QCS/IR/QCSOps.td"

#endif // PYTHON_BINDINGS_QCS_OPS
