//===- QuirDialect.td - Quir dialect -----------------------*- tablegen -*-===//
//
// (C) Copyright IBM 2021.
//
// Any modifications or derivative works of this code must retain this
// copyright notice, and modified files need to carry a notice indicating
// that they have been altered from the originals.
//
//===----------------------------------------------------------------------===//

#ifndef QUIR_TD
#define QUIR_TD

include "Dialect/QUIR/IR/QUIRDialect.td"

#endif // QUIR_TD
